on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
jobs:
  check_news_file:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          sudo apt-get -y install jq
          jq '.pull_request.labels | .[].name' "$GITHUB_EVENT_PATH"
