name: news-file
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
jobs:
  pr:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get install -y patchutils curl grep jq
      - name: Check if PR contains a news fragment or has trivial label
        run: |
          echo '::group::Event payload'
          jq . "$GITHUB_EVENT_PATH"
          ::endgroup::
          if jq --exit-status '.pull_request.labels | any(.[].name; . == "trivial")' "$GITHUB_EVENT_PATH"; then
            echo TRIVIAL LABEL
          else
            DIFF_URL="$(jq '.pull_request.diff_url' "$GITHUB_EVENT_PATH")"
            NEWS_FRAGMENT_RE='news/[^\./]+\.(process|removal|feature|bugfix|doc|vendor|trivial)\.rst$'
            printf '%s\n' "$DIFF_URL"
            if curl -L "$DIFF_URL" | lsdiff | grep -E "$NEWS_FRAGMENT_RE"; then
              echo NEWS FRAGMENT
            else
              echo '::error::Missing news fragment or trivial label'
              false
            fi
          fi
