name: news-file
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
jobs:
  pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y curl grep jq
      - name: Check if PR contains a news fragment or has trivial label
        run: |
          set -euo pipefail
          echo '::group::Event payload'
            jq . "$GITHUB_EVENT_PATH"
          echo '::endgroup::'
          if jq --exit-status '.pull_request.labels | any(.[].name; . == "trivial")' "$GITHUB_EVENT_PATH" > /dev/null; then
            echo TRIVIAL LABEL
          else
            PR_URL="$(jq --raw-output '.pull_request.url' "$GITHUB_EVENT_PATH")"
            STATUSES_URL="$(jq --raw-output '.pull_request.statuses_url' "$GITHUB_EVENT_PATH")"
            printf 'PR_URL: %s\nSTATUSES_URL: %s\n' "$PR_URL" "$STATUSES_URL"
            echo "::group::GET $PR_URL/files"
              curl -L -H 'Accept: application/vnd.github.v3+json' "$PR_URL/files" 2>&1 >files.json
              jq . files.json
            echo '::endgroup::'
            NEWS_FRAGMENT_RE='news/[^\./]+\.(process|removal|feature|bugfix|doc|vendor|trivial)\.rst$'
            if jq --raw-output '.[].filename' files.json | grep -E "$NEWS_FRAGMENT_RE" > /dev/null; then
              echo NEWS FRAGMENT
            else
              # echo '::error::Missing news fragment or trivial label'
              echo MISSING
            fi
          fi
