on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
jobs:
  check_news_file:
    runs-on: ubuntu-20.04
    steps:
      - if: ${{ !contains(github.event.pull_request.labels.*.name, 'bug') }}
        run: 'false'
