name: check news file
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
jobs:
  check_news_file:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get install -y patchutils curl grep
      - run: cat "$GITHUB_EVENT_PATH"
      - if: ${{ !contains(github.event.pull_request.labels.*.name, 'trivial') }}
        run: |
          echo "::error::Missing trivial label"
          false
